// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr229mSY6g1Z68V6hdrG3F_Bn15dXxAFI',
    appId: '1:527619297484:web:3fff9b3d9faf12870cb269',
    messagingSenderId: '527619297484',
    projectId: 'cliploops-000',
    authDomain: 'cliploops-000.firebaseapp.com',
    storageBucket: 'cliploops-000.firebasestorage.app',
    measurementId: 'G-LQW08DWD4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqVv7Ip3xtogSKul9T_4oo6Ql062AtHnk',
    appId: '1:527619297484:android:81a94e54c6fc0beb0cb269',
    messagingSenderId: '527619297484',
    projectId: 'cliploops-000',
    storageBucket: 'cliploops-000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnBOsrXvqEMG2Psdz1oIBDRC8FuqpJnFA',
    appId: '1:527619297484:ios:c44f43be7695d3c90cb269',
    messagingSenderId: '527619297484',
    projectId: 'cliploops-000',
    storageBucket: 'cliploops-000.firebasestorage.app',
    iosBundleId: 'com.example.cliploops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnBOsrXvqEMG2Psdz1oIBDRC8FuqpJnFA',
    appId: '1:527619297484:ios:c44f43be7695d3c90cb269',
    messagingSenderId: '527619297484',
    projectId: 'cliploops-000',
    storageBucket: 'cliploops-000.firebasestorage.app',
    iosBundleId: 'com.example.cliploops',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr229mSY6g1Z68V6hdrG3F_Bn15dXxAFI',
    appId: '1:527619297484:web:288ec811a51c2d580cb269',
    messagingSenderId: '527619297484',
    projectId: 'cliploops-000',
    authDomain: 'cliploops-000.firebaseapp.com',
    storageBucket: 'cliploops-000.firebasestorage.app',
    measurementId: 'G-685FFP9RSX',
  );
}
